name: EPython Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Running pyLint
        run: |
          PYTHONPATH=./src/ pylint ./src/epython

      - name: Test with pytest
        run: |
          PYTHONPATH=./src pytest . --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results.xml

  bump-version:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Bump Version
        run: |
          set -xe
          git config --global user.email "codenomad@gmail.com"
          git config --global user.name "Autobot"
          bumpver update
